[platformio]
src_dir = .
include_dir = .

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

; Dependencies required for the project
lib_deps =
    olikraus/U8g2

; You might need to change the COM port to match your system.
; PlatformIO usually auto-detects it.
; upload_port = COM3